import { ActivityDefinition } from './activity.types';

export const ACTIVITY_CATALOG: ActivityDefinition[] = [
  {
    id: 'situational-leadership',
    title: 'El liderazgo que necesita el equipo',
    description: 'Adapta tu forma de liderar a la experiencia y confianza de cada integrante.',
    skill: 'leadership',
    format: 'scenario',
    difficulty: 'beginner',
    durationMinutes: 10,
    scenario: 'Una compañera domina la parte técnica del proyecto, pero duda al presentar sus avances. Otra persona acaba de integrarse y todavía no conoce el proceso.',
    instructions: [
      'Elige cómo acompañarías a cada persona y explica por qué.',
      'Indica qué harías para revisar si el nivel de apoyo está funcionando.',
    ],
    rubric: [
      { criterion: 'Lectura de necesidades', description: 'Distingue la experiencia y confianza de cada integrante.', weight: 35 },
      { criterion: 'Adaptación del liderazgo', description: 'Ajusta dirección y apoyo a cada situación.', weight: 40 },
      { criterion: 'Seguimiento', description: 'Propone una forma respetuosa de revisar el avance.', weight: 25 },
    ],
    sources: ['Liderazgo situacional: el modelo de Hersey y Blanchard explicado paso a paso'],
  },
  {
    id: 'assertive-feedback',
    title: 'Retroalimentación clara y respetuosa',
    description: 'Reformula un comentario difícil para que sea directo, específico y respetuoso.',
    skill: 'communication',
    format: 'practice',
    difficulty: 'beginner',
    durationMinutes: 8,
    scenario: 'En un trabajo grupal, un compañero suele entregar su parte tarde y eso retrasa al resto del equipo.',
    instructions: [
      'Escribe cómo iniciarías la conversación en primera persona.',
      'Describe el efecto concreto de la demora sin atacar a la persona.',
      'Propón un acuerdo verificable para la próxima entrega.',
    ],
    rubric: [
      { criterion: 'Claridad', description: 'Expresa el problema con un ejemplo concreto.', weight: 30 },
      { criterion: 'Respeto', description: 'Evita etiquetas, acusaciones y generalizaciones.', weight: 35 },
      { criterion: 'Acuerdo', description: 'Propone un siguiente paso compartido y específico.', weight: 35 },
    ],
    sources: ['TÉCNICAS PARA PROMOVER LA COMUNICACIÓN ASERTIVA Y FORTALECER LAS RELACIONES INTERPERSONALES EN EL ENTORNO EDUCATIVO'],
  },
  {
    id: 'six-step-decision',
    title: 'Decidir con criterios claros',
    description: 'Aplica un proceso estructurado para resolver una decisión de equipo.',
    skill: 'decision',
    format: 'scenario',
    difficulty: 'intermediate',
    durationMinutes: 12,
    scenario: 'Tu equipo tiene tiempo para preparar solo una de tres propuestas. Dos integrantes prefieren la opción más ambiciosa; el resto teme no terminarla.',
    instructions: [
      'Define el problema y los criterios de éxito.',
      'Pondera los criterios y compara las tres alternativas.',
      'Explica la decisión y qué dato revisarías después para saber si funcionó.',
    ],
    rubric: [
      { criterion: 'Criterios', description: 'Define criterios relacionados con el objetivo y las restricciones.', weight: 30 },
      { criterion: 'Comparación', description: 'Considera más de una alternativa y sus consecuencias.', weight: 35 },
      { criterion: 'Revisión', description: 'Incluye una forma de comprobar y ajustar la decisión.', weight: 35 },
    ],
    sources: ['5 modelos de toma de decisiones que probar si te atascas | The Workstream - Atlassian'],
  },
  {
    id: 'one-two-four-team',
    title: 'Consenso 1-2-4',
    description: 'Prepara una dinámica escalonada para que todas las voces contribuyan.',
    skill: 'teamwork',
    format: 'practice',
    difficulty: 'beginner',
    durationMinutes: 10,
    scenario: 'El grupo debe proponer una mejora para hacer más inclusivo un proyecto universitario, pero en las reuniones suelen hablar las mismas dos personas.',
    instructions: [
      'Formula una pregunta que el equipo pueda resolver.',
      'Describe las etapas individual, pareja, grupo de cuatro y puesta en común.',
      'Explica cómo comprobarías que todas las personas participaron.',
    ],
    rubric: [
      { criterion: 'Secuencia', description: 'Organiza claramente las etapas de reflexión y síntesis.', weight: 35 },
      { criterion: 'Participación', description: 'Incluye una forma de distribuir la voz equitativamente.', weight: 35 },
      { criterion: 'Síntesis', description: 'Define cómo convertir los aportes en una decisión común.', weight: 30 },
    ],
    sources: ['Dinámicas de trabajo colaborativo - AulaPlaneta'],
  },
  {
    id: 'conflict-listening',
    title: 'Mediar un desacuerdo',
    description: 'Facilita una conversación centrada en escuchar, comprender y acordar acciones.',
    skill: 'teamwork',
    format: 'scenario',
    difficulty: 'intermediate',
    durationMinutes: 12,
    scenario: 'Dos integrantes discrepan sobre cómo repartir las tareas. Una persona siente que lleva la mayor carga; la otra dice no haber recibido instrucciones claras.',
    instructions: [
      'Escribe una pregunta neutral para escuchar a cada integrante.',
      'Resume el interés o necesidad de cada parte sin tomar partido.',
      'Propón un acuerdo con responsabilidades y una fecha de revisión.',
    ],
    rubric: [
      { criterion: 'Escucha', description: 'Da espacio a ambas perspectivas y evita asumir intenciones.', weight: 35 },
      { criterion: 'Imparcialidad', description: 'Reformula el desacuerdo sin culpabilizar.', weight: 30 },
      { criterion: 'Acuerdo', description: 'Propone acciones, responsables y seguimiento.', weight: 35 },
    ],
    sources: ['Técnicas para implementar el trabajo en equipo en las empresas - Repositorio UniLibre'],
  },
  {
    id: 'leadership-reflection',
    title: 'Reflexión: una decisión que lideraste',
    description: 'Analiza una experiencia propia y convierte el aprendizaje en una acción futura.',
    skill: 'leadership',
    format: 'reflection',
    difficulty: 'intermediate',
    durationMinutes: 8,
    scenario: 'Recuerda un proyecto, clase o actividad en la que ayudaste a otras personas a avanzar hacia una meta.',
    instructions: [
      'Describe brevemente la situación y tu responsabilidad.',
      'Explica qué hiciste para escuchar, decidir o coordinar.',
      'Identifica qué repetirías y qué cambiarías la próxima vez.',
    ],
    rubric: [
      { criterion: 'Evidencia', description: 'Describe acciones concretas y el contexto.', weight: 30 },
      { criterion: 'Reflexión', description: 'Reconoce efectos, límites y perspectivas de otras personas.', weight: 35 },
      { criterion: 'Transferencia', description: 'Define una acción aplicable a una situación futura.', weight: 35 },
    ],
    sources: ['Diferencia entre el jefe y el líder: guía y ejemplos [2026] - Asana'],
  },
];